[build]
  base = "frontend"
  publish = "dist"  # Frontend build folder
   command = "cd backend && npm run build && cd .. && npm run build"



[functions]
  directory = "backend/functions"  # Path to backend