[build]
  base = "frontend"
  publish = "dist"  # Frontend build folder
  command = "npm run build"



[functions]
  directory = "backend/functions"  # Path to backend
  node_bundler = "esbuild"
  included_files = [
    "backend/projects.json",
    "backend/messages.json"  # Include if file is in parent directory
  ]