[build]
  base = "frontend"
  publish = "dist"  # Frontend build folder
  command = "npm run build"



[functions]
  directory = "backend/functions"  # Path to backend
  node_bundler = "esbuild"
  included_files = ["backend/projects.json"]
  included_files = ["backend/messages.json"]