[build]
  base = "frontend"
  command = "npm run build && cd src/backend && npm install"
  publish = "dist"                     # Vite/React output
  functions = "src/backend"            # Where Netlify finds functions

[dev]
  framework = "vite"
  targetPort = 3000
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200